### PR TITLE
Fix validation (work-around)

### PR DESCRIPTION
**Pull request by cmaumet**
This pull request include updates to make `spm_results.provn` valid according to the [Prov Validator](https://provenance.ecs.soton.ac.uk/validator/view/validator.html) following the introduction of a parent bundle in #56:
1. Fix typos;
2. Repeat namespace definitions inside bundle (as in [this example](https://github.com/lucmoreau/ProvToolbox/blob/master/prov-n/src/test/resources/prov/bundles1.provn));
3. Introduce dummy attributes of each namespace in the parent as a work-around to pass validation.

Here is a minimal example that describes the issue:
1. [This document](https://github.com/lucmoreau/ProvToolbox/blob/master/prov-n/src/test/resources/prov/bundles1.provn) passes the validation.
2. The following document (available [here](https://provenance.ecs.soton.ac.uk/store/documents/2343/)), in which I remove references to the `ex` namespace outside the bundles, does not pass the validation.

<pre>
document
  <s>prefix ex  <http://example.org/example/></s>
  prefix alice  <http://example.org/alice/>
  prefix bob  <http://example.org/bob/>

  entity(bob:bundle1, [prov:type='prov:Bundle'])
  wasGeneratedBy(bob:bundle1, -, 2012-05-24T10:30:00)
  <s>agent(ex:Bob)</s>
  <s>wasAttributedTo(bob:bundle1, ex:Bob)</s>

  entity(alice:bundle2, [ prov:type='prov:Bundle' ])
  wasGeneratedBy(alice:bundle2, -, 2012-05-25T11:15:00)
  <s>agent(ex:Alice)</s>
  <s>wasAttributedTo(alice:bundle2, ex:Alice)</s>

  bundle bob:bundle1
    prefix bob  <http://example.org/bob/>
    prefix ex  <http://example.org/example/>
    entity(ex:report1, [ prov:type="report", ex:version=1 ])
    wasGeneratedBy(ex:report1, -, 2012-05-24T10:00:01)
  endBundle

  bundle alice:bundle2
    prefix alice  <http://example.org/alice/>
    prefix ex  <http://example.org/example/>

    entity(ex:report1)
    entity(ex:report2, [ prov:type="report", ex:version=2 ])
    wasGeneratedBy(ex:report2, -, 2012-05-25T11:00:01)
    wasDerivedFrom(ex:report2, ex:report1)
  endBundle
endDocument
</pre>
1. Adding the `ex` namespace outside of the bundles does not solve the issue (cf. [this document](https://provenance.ecs.soton.ac.uk/store/documents/2344/) which does not pass validation).

@nicholsn, @satra, do you think this behaviour is as expected? If not, could we send feedback to the ProvValidator developers?

### CODE REVIEW

**Comment by satra** [comment]
@cmaumet - prefixes should definitely be allowed outside bundles. i think the prefixes were not properly defined. this doc works.

```
document
  prefix ex  <http://example.com/>
  prefix alice  <http://alice.com>
  prefix bob  <http://bob.com>

  entity(bob:bundle1, [prov:type='prov:Bundle'])
  wasGeneratedBy(bob:bundle1, -, 2012-05-24T10:30:00)
  agent(ex:Bob)
  wasAttributedTo(bob:bundle1, ex:Bob)

  entity(alice:bundle2, [ prov:type='prov:Bundle' ])
  wasGeneratedBy(alice:bundle2, -, 2012-05-25T11:15:00)
  agent(ex:Alice)
  wasAttributedTo(alice:bundle2, ex:Alice)

  bundle bob:bundle1
    entity(ex:report1, [ prov:type="report", ex:version=1 ])
    wasGeneratedBy(ex:report1, -, 2012-05-24T10:00:01)
  endBundle

  bundle alice:bundle2
    entity(ex:report1)
    entity(ex:report2, [ prov:type="report", ex:version=2 ])
    wasGeneratedBy(ex:report2, -, 2012-05-25T11:00:01)
    wasDerivedFrom(ex:report2, ex:report1)
  endBundle
endDocument
```

**Comment by cmaumet** [comment]
Hi @satra. But this document, just slightly modified from yours, does not validate:

```
document
  prefix ex  <http://example.com/>
  prefix alice  <http://alice.com>
  prefix bob  <http://bob.com>

  entity(bob:bundle1, [prov:type='prov:Bundle'])
  wasGeneratedBy(bob:bundle1, -, 2012-05-24T10:30:00)

  entity(alice:bundle2, [ prov:type='prov:Bundle' ])
  wasGeneratedBy(alice:bundle2, -, 2012-05-25T11:15:00)

  bundle bob:bundle1
    entity(ex:report1, [ prov:type="report", ex:version=1 ])
    wasGeneratedBy(ex:report1, -, 2012-05-24T10:00:01)
  endBundle

  bundle alice:bundle2
    entity(ex:report1)
    entity(ex:report2, [ prov:type="report", ex:version=2 ])
    wasGeneratedBy(ex:report2, -, 2012-05-25T11:00:01)
    wasDerivedFrom(ex:report2, ex:report1)
  endBundle
endDocument
```

Do you think this is normal?

**Comment by satra** [comment]
nope! - looking into it.

**Comment by cmaumet** [comment]
Here is a minimal example which does not pass based on your recently [reported issue](https://github.com/lucmoreau/ProvToolbox/issues/94):

```
document
  prefix ex  <http://example.com/>
  prefix other  <http://other.com/>

  entity(ex:bundle1, [prov:type='prov:Bundle'])
  bundle ex:bundle1
    entity(ex:report1, [ prov:type="report", ex:version=1, other:value = "sjhdgdjh" ])
  endBundle
```

From what I have tested, the problem arise each time I _use a prefix in a bundle but not in the parent_ (in this example `other:`).

**Comment by satra** [comment]
@cmaumet - do you mind adding it to the provtoolbox issue

**Comment by cmaumet** [comment]
Sure, I will do it just now.

**Comment by nicholsn** [comment]
Thanks to both of yo for tracking down this bug and providing a work around!

**Comment by satra** [comment]
@nicholsn  - i think we should leave the document as is, no? besides the reordering fix. luc just pointed to the spec that bundles have to appear last. the bug only exists in the web service.

**Comment by nicholsn** [comment]
Thanks, Satra - just now getting back to email. I'll go ahead and amend.

**Pull request merged**
